---
driver:
  network:
  - ["private_network", {ip: "192.168.33.51"}]
  customize:
    memory: 4096
  synced_folders: [["/vagrant/binaries", "/vagrant/binaries"]]
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[df_java::default]
    attributes:
